//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avashortcas
    {
        public int Id { get; set; }
        public string casetitle { get; set; }
        public string area { get; set; }
        public string company { get; set; }
        public string industry { get; set; }
        public string casecode { get; set; }
        public string caseteach { get; set; }
        public Nullable<double> pricers { get; set; }
        public Nullable<double> pricedollar { get; set; }
        public string subject { get; set; }
        public string ordno { get; set; }
        public string @new { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public string pindustry { get; set; }
        public string secindustry { get; set; }
        public string subindustry { get; set; }
        public string AVashortcases_keywords { get; set; }
        public string region { get; set; }
        public string author { get; set; }
        public string centername { get; set; }
        public string SecondaryArea1 { get; set; }
        public string SecondaryArea2 { get; set; }
        public string SecondaryArea3 { get; set; }
        public string SecondaryArea4 { get; set; }
        public string SecondaryArea5 { get; set; }
        public string SecondaryArea6 { get; set; }
        public string Market { get; set; }
        public string Discipline { get; set; }
        public string keywords { get; set; }
        public Nullable<bool> AddToCart { get; set; }
        public string PDF { get; set; }
        public string Description { get; set; }
        public string CaseLength { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public string Organization { get; set; }
        public string Themes { get; set; }
        public string country { get; set; }
    }
}
