//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICMRFaculty
    {
        public int FacultyId { get; set; }
        public string FacultyImage { get; set; }
        public string FacultyName { get; set; }
        public string FacultyDesignation { get; set; }
        public string FacultyQualification { get; set; }
        public string FacultyExperience { get; set; }
        public string FacultyResume { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Details { get; set; }
    }
}
