//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_icmr
    {
        public int sno { get; set; }
        public string userid { get; set; }
        public string prefix { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string add1 { get; set; }
        public string add2 { get; set; }
        public string add3 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string PIN { get; set; }
        public string country { get; set; }
        public string member_qual { get; set; }
        public string member_compname { get; set; }
        public string member_desig { get; set; }
        public string tel_res { get; set; }
        public string tel_off { get; set; }
        public Nullable<decimal> mobile_phone { get; set; }
        public Nullable<decimal> fax { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public string dcname { get; set; }
        public string dophone { get; set; }
        public string mode { get; set; }
        public string EmailAlert { get; set; }
        public Nullable<System.DateTime> Exdate { get; set; }
        public string OrgGST { get; set; }
        public string Password { get; set; }
    }
}
