//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICMREntities2 : DbContext
    {
        public ICMREntities2()
            : base("name=ICMREntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvaCas> AvaCases { get; set; }
        public virtual DbSet<avashortcas> avashortcases { get; set; }
        public virtual DbSet<ICMREvent> ICMREvents { get; set; }
        public virtual DbSet<ICMRFaculty> ICMRFaculties { get; set; }
        public virtual DbSet<ICMRLogin> ICMRLogins { get; set; }
        public virtual DbSet<Master_icmr> Master_icmr { get; set; }
        public virtual DbSet<proccas> proccases { get; set; }
        public virtual DbSet<tblCaseDetail> tblCaseDetails { get; set; }
        public virtual DbSet<tblChapter> tblChapters { get; set; }
        public virtual DbSet<tblEbookCas> tblEbookCases { get; set; }
        public virtual DbSet<tblEbook> tblEbooks { get; set; }
        public virtual DbSet<tblTextBookImg> tblTextBookImgs { get; set; }
        public virtual DbSet<tblTextBook> tblTextBooks { get; set; }
        public virtual DbSet<tblCaseStudy> tblCaseStudies { get; set; }
        public virtual DbSet<tblCaseStudyVolume> tblCaseStudyVolumes { get; set; }
    }
}
