//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proccas
    {
        public int sno { get; set; }
        public string userid { get; set; }
        public string casetitle { get; set; }
        public string noc { get; set; }
        public string notn { get; set; }
        public string amount { get; set; }
        public string TotalAmount { get; set; }
        public string TransactionStatus { get; set; }
        public string TransactionNo { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
    }
}
