//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBlog()
        {
            this.tblBlogImages = new HashSet<tblBlogImage>();
        }
    
        public int BlogId { get; set; }
        public string AuthorName { get; set; }
        public string AuthorImg { get; set; }
        public string AuthorMobileNo { get; set; }
        public string EmailId { get; set; }
        public string CurrentOrg { get; set; }
        public string Designation { get; set; }
        public string BlogContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBlogImage> tblBlogImages { get; set; }
    }
}
