//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCaseStudyVolume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCaseStudyVolume()
        {
            this.tblCaseStudies = new HashSet<tblCaseStudy>();
        }
    
        public int CaseTudyVolumeId { get; set; }
        public string Title { get; set; }
        public string Volume { get; set; }
        public string Category { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IpAdress { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string CoverImg { get; set; }
        public string CasePdf { get; set; }
        public string LocalIpAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCaseStudy> tblCaseStudies { get; set; }
    }
}
