//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCaseStudy
    {
        public int CaseId { get; set; }
        public int CaseTudyVolumeId { get; set; }
        public string CaseTitle { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UserId { get; set; }
        public string SubjectCategory { get; set; }
        public string Category { get; set; }
        public Nullable<int> Year { get; set; }
        public string Month { get; set; }
        public string Casecode { get; set; }
    
        public virtual tblCaseStudyVolume tblCaseStudyVolume { get; set; }
    }
}
