//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEbook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEbook()
        {
            this.tblEbookCases = new HashSet<tblEbookCas>();
        }
    
        public int ebookId { get; set; }
        public string title { get; set; }
        public string volume { get; set; }
        public string category { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string ipadress { get; set; }
        public Nullable<int> pages { get; set; }
        public Nullable<decimal> prise { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public string coverImg { get; set; }
        public string ebookPdf { get; set; }
        public string LocalIpAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEbookCas> tblEbookCases { get; set; }
    }
}
