//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTextBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTextBook()
        {
            this.tblChapters = new HashSet<tblChapter>();
            this.tblTextBookImgs = new HashSet<tblTextBookImg>();
        }
    
        public int TextBookId { get; set; }
        public string Title { get; set; }
        public string Volume { get; set; }
        public string Category { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LocalIpAddress { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> TextBookPages { get; set; }
        public Nullable<int> WorkBookPages { get; set; }
        public Nullable<decimal> TextBookprise { get; set; }
        public Nullable<decimal> WorkBookprise { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string TextBookPdf { get; set; }
        public string Overview { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChapter> tblChapters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTextBookImg> tblTextBookImgs { get; set; }
    }
}
