//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTextBookImg
    {
        public int Id { get; set; }
        public int TextBookId { get; set; }
        public string CoverImage { get; set; }
    
        public virtual tblTextBook tblTextBook { get; set; }
    }
}
