//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVideo
    {
        public int VideoId { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string TypeOfSpeak { get; set; }
        public string CurrentOrg { get; set; }
        public string Designation { get; set; }
        public string VideoURL { get; set; }
    }
}
